package model.user;
public enum LoginMenuMessage {
    USERNAME_DOES_NOT_EXIST,
    USER_REGISTERED_BY_THIS_NAME_BEFORE,
    INCORRECT_USERNAME_AND_PASSWORD,
    USER_LOGED_IN_SUCCESSFULLY,
    USER_REGISTERED_SUCCESSFULLY,
    USER_REGISTERD_BEFORE_BY_THIS_NICKNAME    
}
